# Generated by Django 3.1 on 2020-08-08 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myarticles', '0017_auto_20200729_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentorName', models.CharField(max_length=100)),
                ('CommentorEmail', models.EmailField(max_length=250)),
                ('CommentorComments', models.TextField()),
                ('ArticleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myarticles.myarticle')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FaceBook', models.CharField(max_length=255, unique=True)),
                ('Instagram', models.CharField(max_length=255, unique=True)),
                ('Linkedin', models.CharField(max_length=255, unique=True)),
                ('Twitter', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReplyName', models.CharField(max_length=100)),
                ('ReplyEmail', models.EmailField(max_length=250)),
                ('ReplyComments', models.TextField()),
                ('ArticleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myarticles.myarticle')),
                ('CommentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comments')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Likes', models.BooleanField()),
                ('ArticleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myarticles.myarticle')),
            ],
        ),
    ]
