# Generated by Django 3.0.8 on 2020-07-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubcriberName', models.CharField(max_length=100)),
                ('SubcriberEmail', models.EmailField(max_length=250, unique=True)),
                ('DateOnSubscribe', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
