# Generated by Django 3.0.8 on 2020-07-23 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategorty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSubCategorty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategoryName', models.CharField(max_length=100, unique=True)),
                ('SubCategoryDesc', models.TextField()),
                ('CategoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ArticleCategorty')),
            ],
        ),
    ]
