# Generated by Django 3.0.8 on 2020-07-27 14:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesubcategorty',
            name='SubCategoryDesc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
