# Generated by Django 3.0.8 on 2020-07-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200727_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesubcategorty',
            name='SubCategoryDesc',
            field=models.TextField(),
        ),
    ]
