# Generated by Django 3.0.8 on 2020-07-23 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=200)),
                ('Img', models.ImageField(upload_to='pics')),
                ('Subject', models.TextField()),
                ('Body', models.TextField()),
                ('DatePublished', models.DateTimeField(auto_now_add=True, verbose_name='Published on')),
                ('CategoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ArticleCategorty')),
                ('SubCategoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ArticleSubCategorty')),
            ],
        ),
    ]
