# Generated by Django 3.0.8 on 2020-07-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myarticle',
            name='Title',
            field=models.CharField(max_length=200),
        ),
    ]
