# Generated by Django 3.0.8 on 2020-07-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0005_myarticle_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myarticle',
            old_name='Body',
            new_name='Body1',
        ),
        migrations.AddField(
            model_name='myarticle',
            name='Body2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myarticle',
            name='Body3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myarticle',
            name='Body4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myarticle',
            name='ListHead',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myarticle',
            name='ListInner1',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myarticle',
            name='ListInner2',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myarticle',
            name='ListInner3',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myarticle',
            name='ListInner4',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myarticle',
            name='ListInner5',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
