# Generated by Django 3.0.8 on 2020-07-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0006_auto_20200724_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myarticle',
            name='Body2',
        ),
        migrations.RemoveField(
            model_name='myarticle',
            name='Body3',
        ),
        migrations.RemoveField(
            model_name='myarticle',
            name='Body4',
        ),
        migrations.RemoveField(
            model_name='myarticle',
            name='ListHead',
        ),
        migrations.RemoveField(
            model_name='myarticle',
            name='ListInner1',
        ),
        migrations.RemoveField(
            model_name='myarticle',
            name='ListInner2',
        ),
        migrations.RemoveField(
            model_name='myarticle',
            name='ListInner3',
        ),
        migrations.RemoveField(
            model_name='myarticle',
            name='ListInner4',
        ),
        migrations.RemoveField(
            model_name='myarticle',
            name='ListInner5',
        ),
    ]
