# Generated by Django 3.0.8 on 2020-07-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0007_auto_20200724_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='myarticle',
            name='Body2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myarticle',
            name='Body3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myarticle',
            name='Body4',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myarticle',
            name='ListHead',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myarticle',
            name='ListInner1',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myarticle',
            name='ListInner2',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myarticle',
            name='ListInner3',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myarticle',
            name='ListInner4',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myarticle',
            name='ListInner5',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
