# Generated by Django 3.0.8 on 2020-07-24 10:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0011_auto_20200724_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myarticle',
            name='Body1',
            field=tinymce.models.HTMLField(),
        ),
    ]
