# Generated by Django 3.0.8 on 2020-07-27 06:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0013_auto_20200724_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myarticle',
            name='Body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
