# Generated by Django 3.0.8 on 2020-07-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0014_auto_20200727_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='myarticle',
            name='File',
            field=models.FileField(default=1, upload_to='docs/'),
            preserve_default=False,
        ),
    ]
