# Generated by Django 3.0.8 on 2020-07-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0015_myarticle_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myarticle',
            name='File',
            field=models.FileField(blank=True, upload_to='docs/'),
        ),
    ]
